# Generated by Django 5.2.13 on 2026-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_groupinvite_expires_at_settlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvite',
            name='accepted',
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
